CHAPTER := 05.hello-kernel
MODULES := mbr loader kernel

mbr_SRC := mbr.S
mbr_OFFSET := 0

loader_SRC := loader.S
loader_OFFSET := 1

kernel_SRC := kernel.c
kernel_OFFSET := 9
kernel_LDFILE := link.ld

include ../Makefile.inc
